name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}   # bisa trigger manual dari tab Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          proxy_command: ""
          command_timeout: 30m
          script_stop: true
          # known_hosts untuk verifikasi host (anti MITM)
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          script: |
            set -e
            cd /var/www/kp-procurement-app
            # jaga ownership
            sudo chown -R ${USER}:www-data .
            # jalankan script deploy
            ./deploy.sh